### ISSUE TITLE
[Bug]: Unable to tap upper layer after clicking the lower layer more than one time

### ISSUE THREAD

**Issue by faiyazz-shaikh** [hm21/pro_image_editor#302] opened 2024-12-28 06:01 UTC
### Package Version

7.0.1

### Flutter Version

3.24.5

### Platforms

Android, Web

### How to reproduce?

Create painting layer one large and one small, place smaller layer on top of the larger layer.
Now click on the the lower layer more than one time, now click on upper layer. it's unable to click and not even selecting the layer.

https://github.com/user-attachments/assets/1bc5d539-e83e-422d-8634-aa476b68c091

**Comment by hm21** [comment] 2024-12-28 07:59
Thank you for your report. This issue is a duplicate of #282. Please refer to that issue for updates and additional information.

**Closed as completed by hm21** 2024-12-28 07:59 UTC
Labels: bug, duplicate
