### ISSUE TITLE
[Bug]: Compilation issue on Android

### ISSUE THREAD

**Issue by Abhishek01039** [hm21/pro_image_editor#142] opened 2024-06-26 07:49 UTC
### Package Version

4.1.1

### Flutter Version

3.19.6

### Platforms

Android

### How to reproduce?

Run the app on android

### Logs (optional)

```sh
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
../../../.pub-cache/hosted/pub.dev/pro_image_editor-4.1.1/lib/utils/content_recorder.dart/content_recorder_controller.dart:409:9: Error: No named parameter with the name 'logicalConstraints'.
        logicalConstraints: BoxConstraints(
        ^^^^^^^^^^^^^^^^^^
../../../Downloads/flutter/packages/flutter/lib/src/rendering/view.dart:23:9: Context: Found this candidate, but the arguments don't match.
  const ViewConfiguration({
        ^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDevDebug'.
> Process 'command '/Users/abhishek/Downloads/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).
```

### Device Model (optional)

Android emulator(android 14)

**Comment by hm21** [comment] 2024-06-26 07:55
Thank you for your feedback. This issue appears to be a duplicate of issue #117. To keep the discussion centralized, I'll close this one.

**Closed as completed by hm21** 2024-06-26 07:55 UTC
Labels: bug, duplicate
