### ISSUE TITLE
[Feature request] Helper lines for aligning items with each other

### ISSUE THREAD

**Issue by adamkoch** [hm21/pro_image_editor#66] opened 2024-06-07 11:27 UTC
### Platforms

Android, iOS, Web

### Description

First of all - awesome library, thanks for creating and sharing it.

Feature request - the helper lines for aligning with center or with certain rotation angles are great.

Helper lines for aligning items with each other would also be really helpful. For example, if you position some text somewhere and then add another item, if a helper line would appear to make sure they are both lined up with each other.

Example:
![Simulator Screenshot - iPhone 15 Pro - 2024-06-07 at 21 23 56](https://github.com/hm21/pro_image_editor/assets/869261/ec40d110-ac64-42ea-b35d-042dbeeefc91)

Thanks again!

### Why

Keeping items aligned with each other easily is helpful and looks a lot better!

**Comment by hm21** [comment] 2024-06-07 12:16
Thanks for your feature request and great to hear you like my package :)

I put your future request in my [roadmap](https://github.com/users/hm21/projects/7), so I will close it here. 


To be honest, that future request will be a small challenge, and in some case near to impossible without use a lot of CPU usage. To show a line when two layers have the same center point is easy because that's the zero offset position of the layer. But the problem is when we want to show a line like in your image where two layers align on the same side. 

The challenge here is that the layer width can be different as it looks like. As example, when you use a desktop platform and put an emoji inside, you will see the mouse cursor will already change even you didn't directly hover the emoji. That's because flutter renders a rectangle hit box over text widgets, which is mostly a bit bigger than the emoji and this gives us also a wrong rendered widget size back. When you draw a painting you will see the hit box is near to perfect because in custom paintings we have the possibility to write or own hit box detection.

This means that for your feature request, I first need to find another solution that renders the stuff differently with the same width that we see. My current plan is that I need to convert each layer to an image, where I must remove all transparent areas that shrink the width and height to the correct size. The code to remove the transparent area, I already wrote [here](https://github.com/hm21/pro_image_editor/blob/stable/lib/utils/content_recorder.dart/utils/convert_raw_image.dart). The problem is I think it will overload the CPU and RAM fast if I create for every layer an image because the image for the layer must be in a high quality for the case the user change the size of the layer.

Anyway, when I find time, I will make some tests and consider than which solution is the best. :)

**Closed as completed by hm21** 2024-06-07 12:16 UTC
Labels: enhancement

**Comment by adamkoch** [comment] 2024-06-07 12:49
Thanks for the detailed explanation. It sounds complicated 😬 Will leave it with you. Thanks again.
