### ISSUE TITLE
[Bug]: button overflowing 

### ISSUE THREAD

**Issue by HeropolisDa2ny** [hm21/pro_image_editor#173] opened 2024-07-26 15:00 UTC
### Package Version

4.3.0

### Flutter Version

3.22.3

### Platforms

Android

### How to reproduce?

With `ProImageEditor.memory`, select the paint option.
The top bar will have a right overflowing icon.

<img width="306" alt="Screenshot 2024-07-26 at 8 57 49" src="https://github.com/user-attachments/assets/565dee9a-afaf-4765-b95b-8e8bd72be215">

**Comment by hm21** [comment] 2024-07-27 06:48
I just tried it on Android but in my case everything works fine. Can you try if you have this issue as well when you remove all configs from the image editor? And if yes, can you fork the sample code and try if it works as correct? This will help to check if the problem is on your code, a specific device or some configuration on the editor.

**Comment by HeropolisDa2ny** [comment] 2024-07-29 14:11
> I just tried it on Android but in my case everything works fine. Can you try if you have this issue as well when you remove all configs from the image editor? And if yes, can you fork the sample code and try if it works as correct? This will help to check if the problem is on your code, a specific device or some configuration on the editor.

Here's my code without anything but the image :

```
return ProImageEditor.memory(
  image,
  callbacks: ProImageEditorCallbacks(
    onImageEditingComplete: (bytes) async {},
    onCloseEditor: () {},
  ),
  // configs: configs,
);
```

Here's the different tabs :

<img width="316" alt="Screenshot 2024-07-29 at 8 06 17" src="https://github.com/user-attachments/assets/c5c23ee7-8ae1-48f8-8684-31f0cad50f11">
<img width="315" alt="Screenshot 2024-07-29 at 8 06 42" src="https://github.com/user-attachments/assets/a21260ad-ddff-4607-9708-e2ef6e3f6d25">
<img width="317" alt="Screenshot 2024-07-29 at 8 06 50" src="https://github.com/user-attachments/assets/cd8c2d3e-489a-428b-bfdf-5cf093989eb1">
<img width="317" alt="Screenshot 2024-07-29 at 8 07 03" src="https://github.com/user-attachments/assets/8851e2fd-bfbe-4208-a3fc-bcb5b45cceb3">
<img width="318" alt="Screenshot 2024-07-29 at 8 07 11" src="https://github.com/user-attachments/assets/0f2fdcde-e6b8-4910-bdbc-980c28f3833e">

Here's the details of my emulator :

<img width="525" alt="Screenshot 2024-07-29 at 8 11 32" src="https://github.com/user-attachments/assets/75f6529a-1b5c-481a-9fa3-1c3e2f824a0a">

**Comment by HeropolisDa2ny** [comment] 2024-07-29 14:51
I made a PR to resolve the problem : https://github.com/hm21/pro_image_editor/pull/177 but it includes spacing modification.

**Comment by hm21** [comment] 2024-07-30 07:36
Great job, I just merged it and will release the new version.

**Closed as completed by hm21** 2024-07-30 07:36 UTC
Labels: bug

**Comment by HeropolisDa2ny** [comment] 2024-07-30 14:27
@hm21 
Here another overflowing fix : https://github.com/hm21/pro_image_editor/pull/178 it includes agencement modifications and an add of option.
